### ISSUE TITLE
Can't compile the sample

### ISSUE THREAD

**Issue by dmitryhryppa** [ianharrigan/hxWidgets#26]
Hi there,
can't get it working with hxcpp 3.2.205

Here is the errors what I got:
```
Window.cpp
./src/hx/widgets/Window.cpp(1219): error C2440: 'return': cannot convert from 'null' to 'wxWindow *'
./src/hx/widgets/Window.cpp(1219): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called

Brush.cpp
EvtHandler.cpp
BoxSizer.cpp
Error: Build failed
Press enter to exit...
```

Did I miss something?

**Comment by ianharrigan** [comment]
You need git hxcpp currently.

**Comment by dmitryhryppa** [comment]
Now it's fine :) Thanks!
